VaultKeeper/Password_Manager/urls.py
from django.urls import path, reverse, reverse_lazy, include
from . import views

app_name = 'Password_Manager'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('passwords/', views.password_view, name='passwords'),
    path('passwords/delete/<int:pk>', views.delete_view, name='delete'),
    path('about/', views.about_view, name='about'),
    path('accounts/signup/', views.signup_view, name='signup'),
    path('accounts/login/', views.CustomLoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/passwords/', views.password_view),
    path('accounts/logout/thankyou/', views.thankyou_view, name='thankyou'),
    path('comingsoon/', views.comingsoon, name='comingsoon')
]

VaultKeeper/VaultKeeper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Password_Manager.urls")),
]

VaultKeeper/Password_Manager/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


# Create your models here.

class Password(models.Model):
    website = models.URLField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='passwords')

VaultKeeper/Password_Manager/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


# class login_form(forms.Form):
#     username = forms.CharField(label='Username', max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
#     password = forms.CharField(label='Password', max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))



class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label='Username', max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', max_length=255, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class signup_form(forms.Form):
    username = forms.CharField(label='Username', max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', max_length=255, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class password_form(forms.Form):
    link = forms.URLField(label='Link', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'www.example.com'}))
    account = forms.CharField(label='Account', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'example@email.com'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '**********'}))

VaultKeeper/Password_Manager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Password, User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from . import forms
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.auth.password_validation import validate_password
from django.contrib.messages.views import SuccessMessageMixin
from django.conf import settings

substitution_key = settings.KEY

# Create your views here.

def index_view(request):
    context = {}
    # return HttpResponse("HELLO")
    return render(request, "Password_Manager/index.html", context = context)

def encrypt(message, key):
    encrypted_message = ""
    for char in message:
        if char.lower() in key:
            encrypted_message += key[char.lower()]
        else:
            encrypted_message += char
    return encrypted_message

# Define a function to decrypt the message
def decrypt(message, key):
    decrypted_message = ""
    for char in message:
        if char.lower() in key.values():
            for k, v in key.items():
                if v == char.lower():
                    decrypted_message += k
        else:
            decrypted_message += char
    return decrypted_message



@login_required
def password_view(request):
    # print("ONE")
    if request.POST:
        form = forms.password_form(request.POST)
        # print("TWO")
        if form.is_valid():
            # print("THREE")
            
            link = form.cleaned_data['link']
            account = form.cleaned_data['account']
            password = form.cleaned_data['password']
            user = request.user
            password = encrypt(password, substitution_key)
            Password.objects.create(website=link, username=account, password=password, user=user)
            return redirect(reverse('Password_Manager:passwords'))
    user = request.user.pk
    name = request.user.username
    passwords = Password.objects.filter(user=user)
    for i in passwords:
        i.password = decrypt(i.password, substitution_key)

    return render(request, "Password_Manager/passwords.html", context = {'passwords': passwords, 'user':name.capitalize(), 'password_form': forms.password_form, 'userID':user})


def about_view(request):
    return render(request, "Password_Manager/about.html")


# def login_view(request):
    # if request.POST:
    #     username = request.POST.get('username').lower()
    #     password = request.POST.get('password')
    #     print(password)
    #     user = authenticate(request, username=username, password=password)

    #     if user is not None:
    #         login(request, user)
    #         return redirect(reverse('Password_Manager:passwords'))
    #     else:
    #         error_message = 'Invalid username or password!'
    #         return render(request, "registration/login.html", {'form':form, 'error':error_message})
    # else:
    #     form = forms.login_form()
    # return render(request, "registration/login.html", {'form':form})



def signup_view(request):
    if request.method == 'POST':
        form = forms.signup_form(request.POST)
        if form.is_valid():
            # validate password
            password = form.cleaned_data['password']
            try:
                validate_password(password)
            except Exception as e:
                # form.add_error('password', str(e))
                return render(request, 'registration/signup.html', {'form': form, 'errors': e})

            # create user
            username = form.cleaned_data['username'].lower()
            print(password)

            User.objects.create_user(username=username, password=password)
            user_auth = authenticate(request, username=username, password=password)
            if user_auth is not None:
                login(request, user_auth)
            return redirect(reverse('Password_Manager:passwords'))
    else:
        form = forms.signup_form()
    return render(request, "registration/signup.html", {'form': form})


def delete_view(request, pk):
    # print(userID)
    # for i in Password.objects.filter(user = User.objects.get(id=userID)):
    #     print(i.id)
    # print(request.user.username)
    # print(get_object_or_404(Password, pk=pk).user.username)
    print("START")
    print(f"pk is {pk}")
    try:
        password = Password.objects.filter(user=User.objects.get(id=request.user.id))[pk-2]
        print(password)
        if request.user.id == password.user.id:
            password.delete()
            return redirect(reverse('Password_Manager:passwords'))
        else:
            return HttpResponse("Do you not have permission to delete this password")
    except:
        return HttpResponse("Something went wrong!")
    

def logout_view(request):
    logout(request)
    # return render(request, 'Password_Manager/thankyou.html')


def thankyou_view(request):
    return render(request, 'Password_Manager/thankyou.html')

def comingsoon(request):
    return render(request, 'Password_manager/comingsoon.html')



class CustomLoginView(LoginView):
    authentication_form = forms.CustomAuthenticationForm

VaultKeeper/Password_Manager/templates/Password_Manager/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="{% static 'Password_Manager/329.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'Password_Manager/329.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400&display=swap" rel="stylesheet">
    <title>Vault Keeper</title>
</head>
<body> 
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-0" style="background-color:#76b5c5;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'Password_Manager:index' %}"><img src="https://assets.materialup.com/uploads/53a51966-b17f-4f52-a2d8-e34c38b12d5c/preview" alt="Logo" width="60" class="d-inline-block align-text-top"></a>
      <a class="navbar-brand" href="{% url 'Password_Manager:index' %}" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: white; font-size: 2em">Vault Keeper</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Password_Manager:passwords' %}">Passwords</a>
          </li> 
          {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Password_Manager:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'Password_Manager:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  
  
  {% block content %}
  
  {% endblock content %}
</body>

</html>

VaultKeeper/Password_Manager/templates/Password_Manager/comingsoon.html
{% extends 'Password_Manager/base.html' %}
  
{% block content %}

      <div class="container-fluid bg-light p-5" style="width: 98.6%; border-radius: 8px;">
        <h1 class="display-4" style ="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: black;">Coming soon...?</h1>
        <p>Just kidding, this is just a joke page for a hypothetical premium plan.</p>



    </div>
    

{% endblock content %}

VaultKeeper/Password_Manager/templates/Password_Manager/index.html
{% extends 'Password_Manager/base.html' %}
{% block content %}
{% load static %}

<body style="background-color:#e1e6e2">
  
  <div class="container-fluid p-5" style="background-color:#212629;">
    <div class="row">
      <div class="col-md-8">
        <h1 class="display-4" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: white;">Experience peace of mind <br> with our easy-to-use, secure <br> password manager.</h1>
        {% if request.user.is_authenticated %}
          <p class="lead" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: #c8c7cd;">You are logged in</p>
        {% else %}
          <p class="lead" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: #c8c7cd;">Log in to start!</p>
        {% endif %}
  
        <hr class="my-4">
        <button type="button" class="btn" style="background-color:#e1e6e2; font-family: 'Josefin Sans', sans-serif; font-weight:400; color: black;"> <a href="{% url 'Password_Manager:comingsoon'%}" style="text-decoration:none; color:black">Vault Keeper Plus</a></button>
        <br><br>
        <br><br>
      </div>
      <div class="col-md-4">
        <h1 style="color:white">Need password ideas?</h1>
        <button type="button" class="btn" onclick="generatePassword()" style="background-color:#e1e6e2; font-family: 'Josefin Sans', sans-serif; font-weight:400; color: black;">Generate Password</button>
        <br>
        <textarea id="password" readonly style="width: 35%; height: 35px; font-family: 'Josefin Sans', sans-serif; font-weight:400; color: black;"></textarea>
      </div>
    </div>
  
    <button type="button" class="btn" style="background-color:#e1e6e2; font-family: 'Josefin Sans', sans-serif; font-weight:400; color: black;"> <a href="{% url 'Password_Manager:about' %}" style="text-decoration:none; color:black">About us</a> </button>
  
    <p></p>
  </div>
  
  <script>
    function generatePassword() {
      var password = '';
      var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()-_=+[{]}\\|;:\'",<.>/?';
      var length = 28;
  
      for (var i = 0; i < length; i++) {
        password += characters.charAt(Math.floor(Math.random() * characters.length));
      }
      document.getElementById('password').value = password;
    }
  </script>
  


  <br><br><br>

  <div class="container-fluid p-5" style="width: 98.6%; background-color:#212629">
    <h1 class="display-4" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: white;">Why should we use the Vault Keeper password management tool to secure our sensitive data?</h1>
    <p class="lead"></p>
    <hr class="my-4">
    <p style = "font-family: 'Josefin Sans', sans-serif; font-weight:400; color: #c8c7cd;" = >Using a password management tool like Vault Keeper can help ensure the security of sensitive data by creating and storing strong, unique passwords for each account or system. This reduces the risk of weak passwords or password reuse, which can be exploited by attackers to gain unauthorized access to sensitive data. Vault Keeper can also provide secure 
      storage for other sensitive information such as credit card details, identification documents, or secure notes.
      <br> Due to people frequently using the same passwords or choosing weak ones that are simple to guess, there has been an increase in password-related security breaches. According to Verizon’s 2022 Data Breach Investigations Report, 81% of the hacking related data breaches are due to weak or stolen passwords. This is up from 63% in 2016, 
      also according to Verizon’s report, indicating a clear upward trend in password-related security breaches.
        keeps your passwords safe and secure with a strong encryption algorithm.
      <br><br></p>
    <p class="text-center" style = "font-family: 'Josefin Sans', sans-serif; font-weight:400; color: #c8c7cd; font-size: 2em">  Never forget a password again with Vault Keeper by your side!</p>
    </div>

    <br><br><br>

    <div class="row mx-md-n5">
      <div class="col px-md-5">
        <div class="p-3" style="height:460px; background-color:#212629">
          <h1 class="my-4; text-center" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: white;">EASY</h1>
          <img src="{% static 'images/finger.jpg' %}" style="display:block; margin:auto; max-width:38%; height:auto;" alt="Finger">
          <p class="text-center" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: #c8c7cd;"> Vault Keeper's user-friendly interface and intuitive design makes it easy for you to navigate and manage your passwords, and our password generator makes it easy to create strong, unique passwords for each account.
          </p>
        </div>
      </div>
      <div class="col px-md-5">
        <div class="p-3" style="height:460px; background-color:#212629">
          <h1 class="my-4; text-center" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: white;">SECURE</h1>
          <img src="{% static 'images/secure.jpg' %}" style="display:block; margin:auto; max-width:38%; height:auto;" alt="Finger">
          <p class="text-center" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: #c8c7cd;"> Vault Keeper uses the substitution encryption to protect your passwords and other sensitive information, making it virtually impossible for hackers to access your data.</p>
        </div>
      </div>
    
      <div class="col px-md-5">
        <div class="p-3" style="height:460px; background-color:#212629">
          <h1 class="my-4; text-center" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: white;">RELIABLE</h1>
          <img src="{% static 'images/reliable.jpg' %}" style="display:block; margin:auto; max-width:38%; height:auto;" alt="Finger">
          <p class="text-center" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: #c8c7cd;"> Vault Keeper's advanced encryption algorithms ensure that your passwords are secure and protected from hackers and other malicious actors.</p>
        </div>
      </div>
    </div>
    
    
    <br><br><br>

    <div class="container-fluid p-5" style="width: 98.6%; height: 400px; background-color:#212629">
      <h1 class="display-4 text-center" style="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: white;">Protecting your privacy and securing your digital life, one password at a time.</h1>
      <p class="lead"></p>
      <hr class="my-4">
      <h2 class="my-4" style = "font-family: 'Josefin Sans', sans-serif; font-weight:400; color: #c8c7cd; font-size: 1.5em">Reach out to us!<a href="https://www.instagram.com/"><img src="https://upload.wikimedia.org/wikipedia/commons/9/95/Instagram_logo_2022.svg" style="height:30px; padding-left:10px" alt="Instagram logo"></a></h2>
      
      
      
      <p class = "text-center">&copy Vault Keeper 2023</p>
      </div>
    </body>

{% endblock %}

VaultKeeper/Password_Manager/templates/Password_Manager/passwords.html
{% extends 'Password_Manager/base.html' %}

{% block content %}
{% load static %}


<div class="container-fluid bg-light p-5" style="width: 79%; border-radius: 8px;">
  <h1 class="display-4" style ="font-family: 'Josefin Sans', sans-serif; font-weight:400; color: black;">Welcome {{user}}</h1>
  <p class="lead">You can now start storing your passwords by clicking on "add" and entering your valid credentials.</p>
  <hr class="my-4">


  <div class="row">
  {% for stuff in passwords %}
    <div class="col-sm-6 py-3" data-card-id="{{forloop.counter}}">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><div id="rightCardText">
            <div><img height="16" id="favi" width="16" src='http://www.google.com/s2/favicons?domain={{stuff.website}}'> {{stuff.website}} </div>
            <div id="rightCardFill"></div>
            <div><img src=" {% static 'images/closed-trash-can.png' %} " width="40px" id="trashcan" data-bs-toggle="modal" data-bs-target="#deleteModal{{forloop.counter}}" onmouseover="hover(this);" onmouseout="hoverOut(this)"></div></h5>
            <div class="row">
              <div class="col-md-6">
                <div class="input-group mb-3">
                  <input type="text" id="copyUser{{forloop.counter}}" class="form-control" placeholder="Recipient's username" value="{{stuff.username}}" aria-describedby="button-addon2" readonly>
                  <button class="btn btn-outline-secondary" type="button" id="copyButton" onclick="copyUser({{forloop.counter}})" > copy</button>
                </div>
              </div>
              <div class="col-md-6">
                <div class="input-group mb-3">
                  <input type="password" id="copyText{{ forloop.counter }}" class="form-control" placeholder="Recipient's username" value="{{stuff.password}}" aria-label="Recipient's username" aria-describedby="button-addon2" readonly>
                  <button class="btn btn-outline-secondary" onclick="copy({{ forloop.counter }})" id="liveAlertBtn" type="button">copy</button>
                </div>
              </div>
            </div>        
          <a href="{{stuff.website}}" class="btn btn-primary">Take me there!</a>
        </div>
      </div>
    </div>  

    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModal{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Delete {{stuff.website}} Card</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Are you sure you want to delete this password?
          </div>
          <div class="modal-body">
            This change cannot be undone
          </div>
          <div class="modal-footer" id="opposite_sides">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Don't Delete</button>
            <button type="button" class="btn btn" style="background-color: #c40202; color: white"><a href="{% url 'Password_Manager:delete' forloop.counter|add:1 %}">Delete</a></button>
          </div>
        </div>
      </div>
    </div>
    <!-- End of Delete Modal -->



  {% endfor %}



<!-- New Password Card -->
  <div class="col-sm-6 py-3">
    <div class="card" style="border: dashed; height:173px">
      <div class="card-body">
        <h5 class="card-title"><div id="rightCardText">
          <div>Add new password</div>
          <div id="rightCardFill"></div></h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#passwordForm">
          Add
        </button>
      </div>
    </div>
  </div>
<!-- End of New Password Cards -->




     

<!-- Add Password Form Modal       -->
<div class="modal fade" id="passwordForm" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Account</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <form method="POST">
          {% csrf_token %}
          {% for field in password_form %}
              <div class="input-group mb-3">
                <label for="{{ field.id_for_label }}" class="input-group-text" style="width: 19%">{{field.label_tag}}</label>
                {{ field }}
              </div>
          {% endfor %}

          <div class="modal-footer" id="opposite_sides">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-warning">Add</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- end of Add Password Form Modal-->
{% endblock  %}

VaultKeeper/Password_Manager/templates/Password_Manager/thankyou.html
{% extends 'Password_Manager/base.html' %}

{% block content %}
    <div class="container-fluid bg-light p-5" style="width: 98.6%; border-radius: 8px; text-align: center;">
    <h1 class="display-4" style="padding:230px; font-family: 'Josefin Sans', sans-serif; font-weight:400; color: black;">Thank you!</h1>
    <p class="lead" style = "font-family: 'Josefin Sans', sans-serif; font-weight:300; color: black;">We hope to see you soon!</p>
    {% comment %} <hr class="my-4"> {% endcomment %}
{% endblock content %}